### ISSUE TITLE
CSS problem with simultaneous hosting of HTTP and HTTPS

### ISSUE THREAD

**Issue by helobru** [glumb/pico_cache#4]
If the cache is generated by a user of the unencrypted HTTP connection, the call over HTTPS may lead to problematic unencrypted elements. In particular, the path to the CSS file applies in this case as insecure and leads with appropriate browser setting to unformatted rendering of the page.

**Comment by glumb** [comment]
Have you tried using protocol relative urls (`//` instead of `http://`, `https://`) to your resources, like `//example.com/css/main.css`.

**Comment by helobru** [comment]
I use `<link rel="stylesheet" href="{{ theme_url }}/style.css" type="text/css" />`.

**Comment by glumb** [comment]
I found that the problem comes from pico using absolute urls, for some reason, and therefore the protocol is hardcoded in the cached files. The *base_url* retrieved in *pico.php* line 289 can however be overridden by a config parameter.

It should also work by setting the `base_url` parameter in you *config.php*.
`$config['base_url'] = '//example.com';`
So you don't have to modify the template and all urls should be consistent.

We could add this to the README to avoid further confusion.
